kind: pipeline
type: kubernetes
name: kackdev
steps:
- name: install
  image: node:12
  commands:
    - set -e
    - npm install

- name: twitter
  image: node:12
  commands:
    - npm run twitter 
  environment:
    TWTR_ASECRET:
      from_secret: TWTR_ASECRET
    TWTR_ATOKEN:
      from_secret: TWTR_ATOKEN
    TWTR_CKEY:
      from_secret: TWTR_CKEY
    TWTR_CSECRET:
      from_secret: TWTR_CSECRET
  when:
    branch:
    - master
    event:
    - push

- name: docker
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/gabbersepp/kackdev
    password:
      from_secret: ghcrio_accesstoken
    username: gabbersepp
  when:
    branch:
    - master
    event:
    - push

- name: deploy
  image: gabbersepp/drone-kubectl
  pull: always
  settings:
    kubernetes_server: https://192.168.2.126:16443
    kubernetes_token:
      from_secret: k8s_token
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_user: deploy
  commands:
    - kubectl delete deployment kackdev -n default
    - kubectl apply -f k8s/deployment.yaml -n default
  when:
    branch:
    - master
    event:
    - push