
FROM node:12.18.1 as node

ARG TWTR_CKEY
ARG TWTR_CSECRET
ARG TWTR_ATOKEN
ARG TWTR_ASECRET

ENV TWTR_CKEY=$TWTR_CKEY
ENV TWTR_CSECRET=$TWTR_CSECRET
ENV TWTR_ATOKEN=$TWTR_ATOKEN
ENV TWTR_ASECRET=$TWTR_ASECRET

WORKDIR /
COPY . .
RUN npm install
RUN npm run twitter 2>&1 | tee out.txt && \
    npm run 11ty

FROM nginx
COPY --from=node /dist /usr/share/nginx/html