apiVersion: v1
kind: PersistentVolume
metadata:
  name: cert-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/etc/letsencrypt/live/h5b.de"