apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kackdev-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - hosts:
    - kack.dev
    secretName: kackdev-ingress-tls
  rules:
  - host: kack.dev
    http:
      paths:
        - path: /idptest
          pathType: ImplementationSpecific
          backend:
            service:
              name: kackdev-idp-service
              port: 
                number: 80
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: kackdev-service
              port: 
                number: 80
  - host: www.kack.dev
    http:
      paths:
        - path: /idptest
          pathType: ImplementationSpecific
          backend:
            service:
              name: kackdev-idp-service
              port: 
                number: 80
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: kackdev-service
              port: 
                number: 80